# Site settings
site: Ephesus
title: written words that wraps our fiber \!
keywords: ephesus, blog, tech, life
description: >-
  All that 
lang: en-US
timezone:  Europe/Istanbul
repo: https://github.com/sanju7/blogs/ # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Sanjay Anand
  bio: Computer Engineer @pardinus <br> Founder @zaqa <br> Open Source /#linux
  picture: assets/images/sa_profiles.png 
  github: sanju7 # github username
  twitter: sanju7 # twitter username
  facebook: sanjay.anand.56808995 # facebook username
  instagram: skipper__big # instagram username
  youtube: https://www.youtube.com/@SanjayAnand1UP # youtube username
  linkedin: sanjay-anand-5599007 # linkedin username
  email: hi@sanjayanand.pro # email adress


# URL settings
url: "https://sanju7.github.io/" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
